version: "3.7"

services:
  app:
    container_name: app
    image: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
       - net-nest


  db:
    image: postgres
    container_name: db
    ports:
      - 54321:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rainbowDatabase
      POSTGRES_PASSWORD: my_strong_password
      POSTGRES_USER: unicorn_user
    networks:
      - net-nest


networks:
    net-nest:
        driver: bridge

volumes:
    postgres-data:
